version: "2.2"
services:
  website:
    container_name: webapp
    image: php:apache
    depends_on:
      - api
    env_file:
      - .env
    ports:
     - 80:80
    volumes:
     - ./website:/var/www/html 
    networks:
    - api-network

  api:
   container_name: student-api
   image: api-student-list:latest
   ports:
    - 5000:5000
   volumes:
    - ./simple_api/student_age.json:/data/student_age.json
   networks:
    - api-network

networks:
  api-network:
    
  
